version: '3.8'
services:
  james:
    image: apache/james:memory-3.8.0  # Memory version doesn't need OpenSearch
    container_name: james-server
    hostname: james.local
    ports:
      - "25:25"
      - "143:143"
      - "993:993"
      - "465:465"
      - "587:587"
      - "8000:8000"
    volumes:
      - ./target/james-extension-rabbitmq-1.0-SNAPSHOT.jar:/root/extensions-jars/james-extension-rabbitmq-1.0-SNAPSHOT.jar:ro
      - ./conf:/root/conf:rw
      - james-data:/root/var
    environment:
      - rabbitmq.host=rabbitmq
      - rabbitmq.port=5672
      - rabbitmq.username=james
      - rabbitmq.password=secret
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - james-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: james-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=james
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - james-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  james-data:
  rabbitmq-data:

networks:
  james-network:
    driver: bridge